//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public enum Units {
    
    /// <remarks/>
    MM,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    PX,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class Area {
    
    private decimal valueField;
    
    private bool valueFieldSpecified;
    
    private Units squareUnitsField;
    
    private bool squareUnitsFieldSpecified;
    
    private decimal confidenceField;
    
    private bool confidenceFieldSpecified;
    
    /// <remarks/>
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValueSpecified {
        get {
            return this.valueFieldSpecified;
        }
        set {
            this.valueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Units SquareUnits {
        get {
            return this.squareUnitsField;
        }
        set {
            this.squareUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SquareUnitsSpecified {
        get {
            return this.squareUnitsFieldSpecified;
        }
        set {
            this.squareUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConfidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class Pose6D {
    
    private Units unitsField;
    
    private bool unitsFieldSpecified;
    
    private decimal xField;
    
    private bool xFieldSpecified;
    
    private decimal yField;
    
    private bool yFieldSpecified;
    
    private decimal zField;
    
    private bool zFieldSpecified;
    
    private decimal yawField;
    
    private bool yawFieldSpecified;
    
    private decimal pitchField;
    
    private bool pitchFieldSpecified;
    
    private decimal rollField;
    
    private bool rollFieldSpecified;
    
    private decimal confidenceField;
    
    private bool confidenceFieldSpecified;
    
    /// <remarks/>
    public Units Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsSpecified {
        get {
            return this.unitsFieldSpecified;
        }
        set {
            this.unitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XSpecified {
        get {
            return this.xFieldSpecified;
        }
        set {
            this.xFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool YSpecified {
        get {
            return this.yFieldSpecified;
        }
        set {
            this.yFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ZSpecified {
        get {
            return this.zFieldSpecified;
        }
        set {
            this.zFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Yaw {
        get {
            return this.yawField;
        }
        set {
            this.yawField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool YawSpecified {
        get {
            return this.yawFieldSpecified;
        }
        set {
            this.yawFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Pitch {
        get {
            return this.pitchField;
        }
        set {
            this.pitchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PitchSpecified {
        get {
            return this.pitchFieldSpecified;
        }
        set {
            this.pitchFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Roll {
        get {
            return this.rollField;
        }
        set {
            this.rollField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollSpecified {
        get {
            return this.rollFieldSpecified;
        }
        set {
            this.rollFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Confidence {
        get {
            return this.confidenceField;
        }
        set {
            this.confidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConfidenceSpecified {
        get {
            return this.confidenceFieldSpecified;
        }
        set {
            this.confidenceFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public enum EyeState {
    
    /// <remarks/>
    FIXATION,
    
    /// <remarks/>
    SACCADE,
    
    /// <remarks/>
    SMOOTH_PURSUIT,
    
    /// <remarks/>
    UNKNOWN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class Pupil {
    
    private Area areaField;
    
    /// <remarks/>
    public Area Area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute("Head", Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class BeingHead {
    
    private Pose6D gazeVectorField;
    
    /// <remarks/>
    public Pose6D GazeVector {
        get {
            return this.gazeVectorField;
        }
        set {
            this.gazeVectorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute("RightEye", Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class BeingEye {
    
    private EyeState eyeStateField;
    
    private bool eyeStateFieldSpecified;
    
    private Pose6D gazeVectorField;
    
    private Pupil pupilField;
    
    /// <remarks/>
    public EyeState EyeState {
        get {
            return this.eyeStateField;
        }
        set {
            this.eyeStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EyeStateSpecified {
        get {
            return this.eyeStateFieldSpecified;
        }
        set {
            this.eyeStateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Pose6D GazeVector {
        get {
            return this.gazeVectorField;
        }
        set {
            this.gazeVectorField = value;
        }
    }
    
    /// <remarks/>
    public Pupil Pupil {
        get {
            return this.pupilField;
        }
        set {
            this.pupilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class Being {
    
    private string identField;
    
    private BeingHead headField;
    
    private BeingEye rightEyeField;
    
    private BeingEye leftEyeField;
    
    private Pose6D gazeVectorField;
    
    /// <remarks/>
    public string Ident {
        get {
            return this.identField;
        }
        set {
            this.identField = value;
        }
    }
    
    /// <remarks/>
    public BeingHead Head {
        get {
            return this.headField;
        }
        set {
            this.headField = value;
        }
    }
    
    /// <remarks/>
    public BeingEye RightEye {
        get {
            return this.rightEyeField;
        }
        set {
            this.rightEyeField = value;
        }
    }
    
    /// <remarks/>
    public BeingEye LeftEye {
        get {
            return this.leftEyeField;
        }
        set {
            this.leftEyeField = value;
        }
    }
    
    /// <remarks/>
    public Pose6D GazeVector {
        get {
            return this.gazeVectorField;
        }
        set {
            this.gazeVectorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class Beings {
    
    private Being[] beingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Being")]
    public Being[] Being {
        get {
            return this.beingField;
        }
        set {
            this.beingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class UnitConversion {
    
    private Units fromUnitsField;
    
    private Units toUnitsField;
    
    private decimal factorField;
    
    /// <remarks/>
    public Units FromUnits {
        get {
            return this.fromUnitsField;
        }
        set {
            this.fromUnitsField = value;
        }
    }
    
    /// <remarks/>
    public Units ToUnits {
        get {
            return this.toUnitsField;
        }
        set {
            this.toUnitsField = value;
        }
    }
    
    /// <remarks/>
    public decimal Factor {
        get {
            return this.factorField;
        }
        set {
            this.factorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class Plane {
    
    private string identField;
    
    private decimal aField;
    
    private decimal bField;
    
    private decimal cField;
    
    private decimal dField;
    
    private UnitConversion unitConversionField;
    
    /// <remarks/>
    public string Ident {
        get {
            return this.identField;
        }
        set {
            this.identField = value;
        }
    }
    
    /// <remarks/>
    public decimal A {
        get {
            return this.aField;
        }
        set {
            this.aField = value;
        }
    }
    
    /// <remarks/>
    public decimal B {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    public decimal C {
        get {
            return this.cField;
        }
        set {
            this.cField = value;
        }
    }
    
    /// <remarks/>
    public decimal D {
        get {
            return this.dField;
        }
        set {
            this.dField = value;
        }
    }
    
    /// <remarks/>
    public UnitConversion UnitConversion {
        get {
            return this.unitConversionField;
        }
        set {
            this.unitConversionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class Surfaces {
    
    private Plane[] planeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Plane")]
    public Plane[] Plane {
        get {
            return this.planeField;
        }
        set {
            this.planeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class Camera {
    
    private string identField;
    
    private Pose6D pose6DField;
    
    /// <remarks/>
    public string Ident {
        get {
            return this.identField;
        }
        set {
            this.identField = value;
        }
    }
    
    /// <remarks/>
    public Pose6D Pose6D {
        get {
            return this.pose6DField;
        }
        set {
            this.pose6DField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class Cameras {
    
    private Camera[] cameraField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Camera")]
    public Camera[] Camera {
        get {
            return this.cameraField;
        }
        set {
            this.cameraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public enum RevisionType {
    
    /// <remarks/>
    NEW,
    
    /// <remarks/>
    REPLACE,
    
    /// <remarks/>
    REMOVE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class GazeTrackDataSet {
    
    private GazeTrackData[] gazeTrackDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GazeTrackData")]
    public GazeTrackData[] GazeTrackData {
        get {
            return this.gazeTrackDataField;
        }
        set {
            this.gazeTrackDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gazegroup.org/GazeTracking.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gazegroup.org/GazeTracking.xsd", IsNullable=false)]
public partial class GazeTrackData {
    
    private System.DateTime timestampField;
    
    private long sequenceNumberField;
    
    private RevisionType revisionTypeField;
    
    private bool revisionTypeFieldSpecified;
    
    private Camera[] camerasField;
    
    private Being[] beingsField;
    
    private Plane[] surfacesField;
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    public long SequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
    
    /// <remarks/>
    public RevisionType RevisionType {
        get {
            return this.revisionTypeField;
        }
        set {
            this.revisionTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RevisionTypeSpecified {
        get {
            return this.revisionTypeFieldSpecified;
        }
        set {
            this.revisionTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Camera[] Cameras {
        get {
            return this.camerasField;
        }
        set {
            this.camerasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Being[] Beings {
        get {
            return this.beingsField;
        }
        set {
            this.beingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Plane[] Surfaces {
        get {
            return this.surfacesField;
        }
        set {
            this.surfacesField = value;
        }
    }
}
